### ISSUE TITLE
Missing dependency - Bitte globale Pakete deinstallieren :))

### ISSUE THREAD

**Issue by frostyandy2k** [ScaleIT-Org/Workflow-App#3]
```
Error: Cannot find module 'mongoose'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)

```

**Comment by frostyandy2k** [comment]
```
Error: Cannot find module 'morgan'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
```

```
Error: Cannot find module 'body-parser'
    at Function.Module._resolveFilename (module.js:542:15)
```

```
Error: Cannot find module 'method-override'
    at Function.Module._resolveFilename (module.js:542:15)
```
```

Error: Cannot find module 'cors'
    at Function.Module._resolveFilename (module.js:542:15)
```

**Comment by Kuhno92** [comment]
fixed 92c01f4e7533ed7e4ab4b1d25176f603b3dc45ba
